CREATE TABLE steam_games (
    game_id BIGINT PRIMARY KEY,
    game_name TEXT,
    release_date DATE,
    estimated_owners TEXT,
    peak_ccu INTEGER,
    required_age INTEGER,
    price NUMERIC(10,2),
    discount INTEGER,
    dlc_count INTEGER,
    supported_languages TEXT,
    full_audio_languages TEXT,
    windows BOOLEAN,
    mac BOOLEAN,
    linux BOOLEAN,
    metacritic_score INTEGER,
    metacritic_url TEXT,
    user_score INTEGER,
    positive INTEGER,
    negative INTEGER,
    achievements INTEGER,
    recommendations INTEGER,
    average_playtime_forever INTEGER,
    average_playtime_2weeks INTEGER,
    median_playtime_forever INTEGER,
    median_playtime_2weeks INTEGER,
    developers TEXT,
    publishers TEXT,
    categories TEXT,
    genres TEXT
);